name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build --stacktrace
      - name: Create Fabric Build artifact
        uses: actions/upload-artifact@v4
        with:
           name: Traincraft-1.20.1 Alpha Fabric
           path: fabric/build/libs/*
      - name: Create Forge Build artifact
        uses: actions/upload-artifact@v4
        with:
           name: Traincraft-1.20.1 Alpha Forge
           path: forge/build/libs/*
      - name: Create Forge Build artifact
        uses: actions/upload-artifact@v4
        with:
           name: Traincraft-1.20.1 Alpha Quilt
           path: quilt/build/libs/*
